### ISSUE TITLE
Investigate inconsistency between output of validate_output.py and debug analysis of nottingham_lembn.py

### ISSUE THREAD

**Issue by lembn** [euandeas/REF-Paper-Selector#6]

**Comment by euandeas** [comment]
This is because I originally designed it to take the outLitst in the format [paper, author, score] as this makes more sense for the output as the focus is on what papers they are submitting. nottingham_lembn.py outputs the outList in the format [author, paper, score].

**Comment by euandeas** [comment]
Both files have now been fixed.

**Comment by lembn** [comment]
That was an issue, but not the main one. The larger problem is that when I run validate_output.py on the outlist produced by nottingham_lembn.py, it reveals two authors with no submitted papers, however, when debugging nottingham_lembn.py and analysing the state of the variables, the authors who are reported as unsubmitted appear to have submitted work within the arrays of the program. Its probably a logic issue somewhere in the replacement process at the end of the algorithm

**Comment by lembn** [comment]
issue fixed
